import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "./globals.css";
import Header from "./layout/Header";
import Footer from "./layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


// Настройка шрифта
const montserrat = Montserrat({
  subsets: ['latin', 'cyrillic'], // поддерживаемые языки
  weight: ['300', '400', '500', '600', '700'], // нужные начертания
  display: 'swap', // для лучшей производительности
  variable: '--font-montserrat', // CSS переменная (опционально)
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className="{montserrat.variable}">
      <body
        style={{ fontFamily: 'var(--font-montserrat)' }}
      >
        <Header></Header>
         <main>
        {children}
        </main>
        <Footer></Footer>
      </body>
    </html>
  );
}
